# Generated by Django 4.2.10 on 2024-02-27 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Invalid ticket id', regex='^TK\\d{8}$')])),
                ('trip_id', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid Trip id', regex='^TP\\d{8}$')])),
                ('traveler_name', models.CharField(max_length=255)),
                ('traveler_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\d{10,15}$')])),
                ('ticket_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('traveler_email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Invalid email', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')])),
            ],
        ),
    ]
